### ISSUE TITLE
"DISABLE" feature doesn't always work

### ISSUE THREAD

**Issue by janezk7** [petermg/TheOcularMigraineMCP#2]
Expected behavior:
Clicking on "DISABLE" should close the app and disable monitoring of app launches and game profile activations.

Actual behavior:
- When I click on DISABLE the app will close. But opening games still activate set profiles. Clicking DISABLE and restarting the device seems to work. 
- It worked as intended when I tried it for the first time, so it seems to work properly at times.

**Comment by petermg** [comment]
Do you have Quest Games Optimizer installed?

**Comment by janezk7** [comment]
No, just OcularMigraine.

**Comment by petermg** [comment]
When you click on DISABLE does The Ocular Migraine close or do you still see the screen?

**Comment by janezk7** [comment]
It closes. 
But I couldn't tell the difference if it only minimized and still ran in the background.

**Comment by petermg** [comment]
I've not experienced this and I am unable to reproduce this. So I will need
you to test something for me. If you think it's still running even though
you clicked on disable, see if you can access the web server it runs. Just
turn the web server on from the Misc screen. Then after you click on
disable from the main screen, see if you can still access the web server of
your device from a computer or phone on the same network.

**Comment by janezk7** [comment]
I'll test this out when I get from work and get back to you

**Comment by janezk7** [comment]
When clicking DISABLE, the server is not accessible anymore. However, game profile still activates.

**Comment by petermg** [comment]
> When clicking DISABLE, the server is not accessible anymore. However, game profile still activates.

If the web server is not accessible anymore, The Ocular Migraine isn't running. Are you are using OVR Metrics tool and looking at the resolution from the home screen and then see it change when launching an application?

**Comment by petermg** [comment]
Ok in this case I need you to do a bit of testing for me. When you see this happening, go to the MISC screen, and click on "Restart Home Environment". When the home environment restarts, what resolution does OVR Metrics Tool show?

**Comment by janezk7** [comment]
When environment restarts, the resolution is whatever I have currently set in MAIN screen. In my case, 2520x2640.

**Comment by petermg** [comment]
> When environment restarts, the resolution is whatever I have currently set in MAIN screen. In my case, 2520x2640.

Just as I thought. Here is what is happening. The Ocular Migraine is actually disabled. However, the resolution is still at whatever it was last time it was changed. The reason it appears to change in OVR Metrics Tool is because in the home environment the resolution doesn't change when you set a different resolution UNLESS you RESTART the home environment. Otherwise when running the OVR Metrics Tool, the home environment shows it's original resolution, but in reality a DIFFERENT, in this case a HIGHER, resolution is set. You then see this when you launch a game or application and it might appear that the resolution is "switching" but in reality no new resolution commands are being issued, and The Ocular Migraine is indeed disabled and not running. This is just whatever resolution you last set it to showing up. This is why when you restart the home environment you then see it running at a higher resolution. I currently do NOT have an implementation to RESET the resolution back to system defaults AUTOMATICALLY after exiting an app. I may look into a way to do this in the near future to prevent this type of confusion.

**Comment by janezk7** [comment]
Got it. Glad we got this sorted out!
