### ISSUE TITLE
Higher resolution activates than it is set 

### ISSUE THREAD

**Issue by janezk7** [petermg/TheOcularMigraineMCP#3]
What I did:
- Set custom resolution to 2520x2640 without setting a game profile and launching the game
- Also tested with setting game profile with same resolution and launching the game

Expected behavior:
- App launches with resolution that was set in OcularMigraine app. 

Actual behavior:
- When starting the app the OVRMonitor reports 2528x2640 (abit off from what was set). Then jumps to a 3536x3696 after few seconds (see recording and screenshot of OcularMigraine settings below)

Additional notes:
- Seems to sometimes work as intended, but sometimes not
- After doing other testing and trying to launch this same game (Ocean Rift), it then worked fine

Suspected cause: 
- Possibly related to #4 

https://github.com/user-attachments/assets/c6452eb1-63f4-49a2-bb24-70b0ae4a8ba0

![com oculus vrshell-20240714-102447](https://github.com/user-attachments/assets/8af377c3-2548-41d7-86c0-d267c2ef01e7)

**Comment by petermg** [comment]
Some games already run at a higher resolution than default. They way they usually do this is by setting a multiplication factor of the device's current resolution. Some even scale the resolution DOWN, like FIRST CONTACT, for example. Others also have the ability to change the resolution from within the application, for example RealVR Fishing has this. In these cases you will see this behavior. I just tested Ocean Rift and this is what is happening. It is automatically set to run at a certain multiple of whatever resolution the headset is set to, so no matter what you set it to, Ocean Rift will ALWAYS run HIGHER since it is purposely trying to run at a higher resolution than the default resolution. In cases like these, it's best NOT to set a resolution profile for it unless you can see using OVR Metrics Tool that there is a lot of horsepower left over that can support even higher resolutions. Closing this since this behavior is not with The Ocular Migraine.

**Comment by janezk7** [comment]
That makes sense. Thanks you for clarification.
